spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  sql.init.mode: always
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

cloud:
  aws:
    s3.bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_BUCKET_ACCESS_KEY}
      secretKey: ${S3_BUCKET_SECRET_KEY}

kakao:
  client-id : ${CLIENT_ID}
  grant-type: ${GRANT_TYPE}
  redirect-url : ${REDIRECT_URL}
  token-url: ${TOKEN_URL}
  user-info-url: ${USER_INFO_URL}
  logout-url: ${LOGOUT_URL}
  user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}

machine-learning:
  server-url: ${MACHINE_LEARNING_SERVER_URL}