spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  sql.init.mode: always
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
